---
- name: Deploy Application and Configure HAProxy
  hosts: localhost
  gather_facts: yes
  tasks:
    - name: Gather Facts
      setup:

    - name: Update package cache
      apt:
        update_cache: yes
      become: yes

    - name: Upgrade packages
      apt:
        upgrade: dist
        update_cache: yes
      become: yes

- name: Configure Servers
  hosts: bastionET2598
  become: yes
  tasks:
    - name: Retrieve IP addresses of instances
      debug:
        msg: "The IP address of {{ item }} is {{ hostvars[item].ansible_default_ipv4.address }}"
      with_items: "{{ groups['webservers'] }}"

- name: Configure HAProxy
  hosts: HAproxy
  become: yes
  tasks:
    - name: Install HAProxy
      apt:
        name: haproxy
        state: present

    - name: Copy HAProxy configuration template
      template:
        src: haproxy.cfg.j2
        dest: /etc/haproxy/haproxy.cfg
      notify: Restart HAProxy

  handlers:
    - name: Restart HAProxy
      service:
        name: haproxy
        state: restarted

- name: Deploy and test the Flask app on webservers
  hosts: webservers
  become: yes
  become_method: sudo
  tasks:
    - name: Webservers update
      apt:
        update_cache: yes

    - name: Install python3-pip
      apt:
        name: python3-pip
        state: latest
        update_cache: yes

    - name: Install Flask
      pip:
        name: flask
        state: latest

    - name: Install Gunicorn
      apt:
        name: gunicorn

    - name: Copy the Flask app code to the servers
      copy:
        src: /$PWD/application2.py  
        dest: /home/ubuntu/application2.py
        owner: ubuntu
        mode: '0644'

    - name: Execute the Flask app deployment
      shell: gunicorn -w 2 -D -b 0.0.0.0:5000 application2:app  # Run the Flask app using Gunicorn

- name: Restart HAProxy on HAproxy host
  hosts: HAproxy
  become: yes
  become_method: sudo
  tasks:
    - name: Restart HAproxy
      become: yes
      service:
        name: haproxy
        state: restarted
